### ISSUE TITLE
Example 4 builds fine but does not recognize input parameters

### ISSUE THREAD

**Issue by jstr045329** [typelead/eta-examples#5]
When I run:

$ git clone https://path/to/repo
$ atlas install --dependencies-only
$ atlas build

That all works fine. Then I type:

$ etlas run -- 1 2 2 4

And get this:

etlas: Unknown target '1'.
There is no component '1'.
The project has no package '1'.

**Comment by Jyothsnasrinivas** [comment]
@jstr045329 Thanks for filing the issue. The README is a bit outdated. The latest etlas doesn't support `etlas run -- 1 2 2 4`. 

I've just updated the README with the latest command `etlas run matrix-ex -- 1 2 3 4`.  

Let me know if encounter anymore problems.

**Comment by Jyothsnasrinivas** [comment]
Closing this issue since it is resolved with the updated README!
